version: '3.4'

networks:
    default:
        driver: bridge

services:
    formula-1-web:
        container_name: formula-1-web
        image: nginx:stable
        volumes:
            - ./Formula-1-Web:/var/www
            - ./Formula-1-Web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        ports:
         - "8080:80"
        environment:
         - NGINX_HOST=formula1.web
         - NGINX_PORT=80
        command: /bin/bash -c "chmod 755 /var/www && exec nginx -g 'daemon off;'"

    formula-1-api:
        container_name: formula-1-api
        image: ${DOCKER_REGISTRY-}formula1api
        networks:
            - default
        build:
            context: .
            dockerfile: Formula-1-API/Dockerfile
        links:
            - db
        environment:
            ASPNETCORE_URLS: https://*:5000
            DBHOST: db
            DBPORT: 3306
            ASPNETCORE_ENVIRONMENT: Development
            DB_CONNECTIONSTRING: ${DB_CONNECTIONSTRING}
        volumes:
            - ./Formula-1-API/Data:/app/Data

    db:
        container_name: formula-1-db
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - default
        ports:
            - "3306:3306"
        volumes:
            - ./Formula-1-API/Data/mysql:/var/lib/mysql
            

