version: '3.4'

networks:
    default:
        name: formula-1-network
        driver: bridge

services:
    web:
        container_name: formula-1-web
        image: formula-1-web
        restart: always
        build: ./ClientApp
        networks:
            - default
        ports:
         - "443:443"
        environment:
         - NGINX_PORT=443
        volumes:
            - ./Data/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./Data/certs/:/etc/ssl:ro
            #- ./Data/certbot/conf:/etc/letsencrypt:ro
            #- ./Data/certbot/www:/var/www/certbot:ro

    api:
        container_name: formula-1-api
        image: formula-1-api
        restart: always
        build: .
        networks:
            - default
        depends_on:
            - db
        environment:
            ASPNETCORE_URLS: https://+:443;http://+:80
            DBHOST: db
            DBPORT: 3306
            ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
            DB_CONNECTIONSTRING: ${DB_CONNECTIONSTRING}
            REDIS_CONNECTIONSTRING: ${REDIS_CONNECTIONSTRING}
            ASPNETCORE_Kestrel__Certificates__Default__Password: ${Certificates_Password}
            ASPNETCORE_Kestrel__Certificates__Default__Path: ${Certificates_Path}
        volumes:
            - ~/.aspnet/https:/https:ro
            - ~/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:ro
            #- ./Data/formula-1-race-data:/app/Data

    db:
        container_name: formula-1-mysql
        image: mysql:8
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - default
        ports:
            - "3306:3306"
        volumes:
            - ./Data/mysql:/var/lib/mysql

    cache: 
        container_name: formula-1-redis
        image: redis:7-alpine
        restart: always
        networks:
            - default
        ports:
            - "6379:6379"
        volumes:
            - ./Data/redis:/usr/local/etc/redis


    #certbot:
    #     container_name: formula-1-certbot
    #     image: certbot/certbot
    #     restart: always
    #     command: /bin/bash -c "certbot certonly --webroot --webroot-path /var/www/certbot/ -d formula1.websites.local"
    #     volumes:
    #        - ./Data/certbot/conf:/etc/letsencrypt:rw
    #        - ./Data/certbot/www:/var/www/certbot:rw
