version: '3.4'

networks:
    default:
        driver: bridge

services:
    web:
        container_name: formula-1-web
        restart: always
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
        networks:
            - default
        links:
            - api
        ports:
         - "443:443"
        environment:
         - NGINX_PORT=443
        volumes:
            - ./Data/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./Data/certs/:/etc/ssl:ro
            #- ./Data/certbot/conf:/etc/letsencrypt:ro
            #- ./Data/certbot/www:/var/www/certbot:ro

    api:
        container_name: formula-1-api
        image: formula-1-api
        restart: always
        networks:
            - default
        ports:
         - "8080:443"
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
        depends_on:
            - db
        environment:
            ASPNETCORE_URLS: https://+:443;http://+:80
            DBHOST: db
            DBPORT: 3306
            ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
            DB_CONNECTIONSTRING: ${DB_CONNECTIONSTRING}
            ASPNETCORE_Kestrel__Certificates__Default__Password: ${Certificates_Password}
            ASPNETCORE_Kestrel__Certificates__Default__Path: ${Certificates_Path}
        volumes:
            #- ./Data/formula-1-race-data:/app/Data
            - ~/.aspnet/https:/https:ro
            - ~/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:ro

    db:
        container_name: formula-1-mysql
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - default
        # ports:
        #    - "3306:3306"
        volumes:
            - ./Data/mysql:/var/lib/mysql

    certbot:
         container_name: formula-1-certbot
         image: certbot/certbot
         # restart: always
         command: /bin/bash -c "certbot certonly --webroot --webroot-path /var/www/certbot/ -d formula1.websites.local"
         volumes:
            - ./Data/certbot/conf:/etc/letsencrypt:rw
            - ./Data/certbot/www:/var/www/certbot:rw
