// <auto-generated />
using System;
using Formula_1_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Formula_1_API.Migrations
{
    [DbContext(typeof(Formula1DbContext))]
    [Migration("20190926160106_CreateFormula1DbContextV1.0")]
    partial class CreateFormula1DbContextV10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Formula_1_API.Models.Circuit", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Lat");

                    b.Property<string>("Lng");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Ref");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Australia",
                            Lat = "-37.8497",
                            Lng = "144.968",
                            Location = "Melbourne",
                            Name = "Albert Park Grand Prix Circuit",
                            Ref = "albert_park",
                            Url = "http://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Malaysia",
                            Lat = "2.76083",
                            Lng = "101.738",
                            Location = "Kuala Lumpur",
                            Name = "Sepang International Circuit",
                            Ref = "sepang",
                            Url = "http://en.wikipedia.org/wiki/Sepang_International_Circuit"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Bahrain",
                            Lat = "26.0325",
                            Lng = "50.5106",
                            Location = "Sakhir",
                            Name = "Bahrain International Circuit",
                            Ref = "bahrain",
                            Url = "http://en.wikipedia.org/wiki/Bahrain_International_Circuit"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Spain",
                            Lat = "41.57",
                            Lng = "2.26111",
                            Location = "Montmel�_",
                            Name = "Circuit de Barcelona-Catalunya",
                            Ref = "catalunya",
                            Url = "http://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Turkey",
                            Lat = "40.9517",
                            Lng = "29.405",
                            Location = "Istanbul",
                            Name = "Istanbul Park",
                            Ref = "istanbul",
                            Url = "http://en.wikipedia.org/wiki/Istanbul_Park"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Monaco",
                            Lat = "43.7347",
                            Lng = "7.42056",
                            Location = "Monte-Carlo",
                            Name = "Circuit de Monaco",
                            Ref = "monaco",
                            Url = "http://en.wikipedia.org/wiki/Circuit_de_Monaco"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Canada",
                            Lat = "45.5",
                            Lng = "-73.5228",
                            Location = "Montreal",
                            Name = "Circuit Gilles Villeneuve",
                            Ref = "villeneuve",
                            Url = "http://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve"
                        },
                        new
                        {
                            Id = 8,
                            Country = "France",
                            Lat = "46.8642",
                            Lng = "3.16361",
                            Location = "Magny Cours",
                            Name = "Circuit de Nevers Magny-Cours",
                            Ref = "magny_cours",
                            Url = "http://en.wikipedia.org/wiki/Circuit_de_Nevers_Magny-Cours"
                        },
                        new
                        {
                            Id = 9,
                            Country = "UK",
                            Lat = "52.0786",
                            Lng = "-1.01694",
                            Location = "Silverstone",
                            Name = "Silverstone Circuit",
                            Ref = "silverstone",
                            Url = "http://en.wikipedia.org/wiki/Silverstone_Circuit"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Germany",
                            Lat = "49.3278",
                            Lng = "8.56583",
                            Location = "Hockenheim",
                            Name = "Hockenheimring",
                            Ref = "hockenheimring",
                            Url = "http://en.wikipedia.org/wiki/Hockenheimring"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.Constructor", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Nationality");

                    b.Property<string>("Ref");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Constructor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "McLaren",
                            Nationality = "British",
                            Ref = "mclaren",
                            Url = "http://en.wikipedia.org/wiki/McLaren"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW Sauber",
                            Nationality = "German",
                            Ref = "bmw_sauber",
                            Url = "http://en.wikipedia.org/wiki/BMW_Sauber"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Williams",
                            Nationality = "British",
                            Ref = "williams",
                            Url = "http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Renault",
                            Nationality = "French",
                            Ref = "renault",
                            Url = "http://en.wikipedia.org/wiki/Renault_F1"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toro Rosso",
                            Nationality = "Italian",
                            Ref = "toro_rosso",
                            Url = "http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ferrari",
                            Nationality = "Italian",
                            Ref = "ferrari",
                            Url = "http://en.wikipedia.org/wiki/Scuderia_Ferrari"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Toyota",
                            Nationality = "Japanese",
                            Ref = "toyota",
                            Url = "http://en.wikipedia.org/wiki/Toyota_Racing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Super Aguri",
                            Nationality = "Japanese",
                            Ref = "super_aguri",
                            Url = "http://en.wikipedia.org/wiki/Super_Aguri_F1"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Red Bull",
                            Nationality = "Austrian",
                            Ref = "red_bull",
                            Url = "http://en.wikipedia.org/wiki/Red_Bull_Racing"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Force India",
                            Nationality = "Indian",
                            Ref = "force_india",
                            Url = "http://en.wikipedia.org/wiki/Force_India"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.ConstructorResult", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConstructorId");

                    b.Property<float>("Points");

                    b.Property<int>("RaceId");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("ConstructorResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructorId = 1,
                            Points = 14f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 2,
                            ConstructorId = 2,
                            Points = 8f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 3,
                            ConstructorId = 3,
                            Points = 9f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 4,
                            ConstructorId = 4,
                            Points = 5f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 5,
                            ConstructorId = 5,
                            Points = 2f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 6,
                            ConstructorId = 6,
                            Points = 1f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 7,
                            ConstructorId = 7,
                            Points = 0f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 8,
                            ConstructorId = 8,
                            Points = 0f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 9,
                            ConstructorId = 9,
                            Points = 0f,
                            RaceId = 18,
                            Status = "NULL"
                        },
                        new
                        {
                            Id = 10,
                            ConstructorId = 10,
                            Points = 0f,
                            RaceId = 18,
                            Status = "NULL"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.ConstructorStanding", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConstructorId");

                    b.Property<float>("Points");

                    b.Property<int>("Position");

                    b.Property<string>("PositionText");

                    b.Property<int>("RaceId");

                    b.Property<int>("Wins");

                    b.HasKey("Id");

                    b.ToTable("ConstructorStandings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructorId = 1,
                            Points = 14f,
                            Position = 1,
                            PositionText = "1",
                            RaceId = 18,
                            Wins = 1
                        },
                        new
                        {
                            Id = 2,
                            ConstructorId = 2,
                            Points = 8f,
                            Position = 3,
                            PositionText = "3",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            ConstructorId = 3,
                            Points = 9f,
                            Position = 2,
                            PositionText = "2",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            ConstructorId = 4,
                            Points = 5f,
                            Position = 4,
                            PositionText = "4",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            ConstructorId = 5,
                            Points = 2f,
                            Position = 5,
                            PositionText = "5",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            ConstructorId = 6,
                            Points = 1f,
                            Position = 6,
                            PositionText = "6",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            ConstructorId = 1,
                            Points = 24f,
                            Position = 1,
                            PositionText = "1",
                            RaceId = 19,
                            Wins = 1
                        },
                        new
                        {
                            Id = 8,
                            ConstructorId = 2,
                            Points = 19f,
                            Position = 2,
                            PositionText = "2",
                            RaceId = 19,
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            ConstructorId = 3,
                            Points = 9f,
                            Position = 4,
                            PositionText = "4",
                            RaceId = 19,
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            ConstructorId = 4,
                            Points = 6f,
                            Position = 5,
                            PositionText = "5",
                            RaceId = 19,
                            Wins = 0
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.Driver", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Dob");

                    b.Property<string>("Forename");

                    b.Property<string>("Nationality");

                    b.Property<int?>("Number");

                    b.Property<string>("Ref");

                    b.Property<string>("Surname");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HAM",
                            Dob = "07/01/1985",
                            Forename = "Lewis",
                            Nationality = "British",
                            Number = 44,
                            Ref = "hamilton",
                            Surname = "Hamilton",
                            Url = "http://en.wikipedia.org/wiki/Lewis_Hamilton"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HEI",
                            Dob = "10/05/1977",
                            Forename = "Nick",
                            Nationality = "German",
                            Ref = "heidfeld",
                            Surname = "Heidfeld",
                            Url = "http://en.wikipedia.org/wiki/Nick_Heidfeld"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ROS",
                            Dob = "27/06/1985",
                            Forename = "Nico",
                            Nationality = "German",
                            Number = 6,
                            Ref = "rosberg",
                            Surname = "Rosberg",
                            Url = "http://en.wikipedia.org/wiki/Nico_Rosberg"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ALO",
                            Dob = "29/07/1981",
                            Forename = "Fernando",
                            Nationality = "Spanish",
                            Number = 14,
                            Ref = "alonso",
                            Surname = "Alonso",
                            Url = "http://en.wikipedia.org/wiki/Fernando_Alonso"
                        },
                        new
                        {
                            Id = 5,
                            Code = "KOV",
                            Dob = "19/10/1981",
                            Forename = "Heikki",
                            Nationality = "Finnish",
                            Ref = "kovalainen",
                            Surname = "Kovalainen",
                            Url = "http://en.wikipedia.org/wiki/Heikki_Kovalainen"
                        },
                        new
                        {
                            Id = 6,
                            Code = "NAK",
                            Dob = "11/01/1985",
                            Forename = "Kazuki",
                            Nationality = "Japanese",
                            Ref = "nakajima",
                            Surname = "Nakajima",
                            Url = "http://en.wikipedia.org/wiki/Kazuki_Nakajima"
                        },
                        new
                        {
                            Id = 7,
                            Code = "BOU",
                            Dob = "28/02/1979",
                            Forename = "S̩bastien",
                            Nationality = "French",
                            Ref = "bourdais",
                            Surname = "Bourdais",
                            Url = "http://en.wikipedia.org/wiki/S%C3%A9bastien_Bourdais"
                        },
                        new
                        {
                            Id = 8,
                            Code = "RAI",
                            Dob = "17/10/1979",
                            Forename = "Kimi",
                            Nationality = "Finnish",
                            Number = 7,
                            Ref = "raikkonen",
                            Surname = "R�_ikk̦nen",
                            Url = "http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C3%B6nen"
                        },
                        new
                        {
                            Id = 9,
                            Code = "KUB",
                            Dob = "07/12/1984",
                            Forename = "Robert",
                            Nationality = "Polish",
                            Ref = "kubica",
                            Surname = "Kubica",
                            Url = "http://en.wikipedia.org/wiki/Robert_Kubica"
                        },
                        new
                        {
                            Id = 10,
                            Code = "GLO",
                            Dob = "18/03/1982",
                            Forename = "Timo",
                            Nationality = "German",
                            Ref = "glock",
                            Surname = "Glock",
                            Url = "http://en.wikipedia.org/wiki/Timo_Glock"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.DriverStanding", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DriverId");

                    b.Property<float>("Points");

                    b.Property<int>("Position");

                    b.Property<string>("PositionText");

                    b.Property<int>("RaceId");

                    b.Property<int>("Wins");

                    b.HasKey("Id");

                    b.ToTable("DriverStandings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            Points = 10f,
                            Position = 1,
                            PositionText = "1",
                            RaceId = 18,
                            Wins = 1
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 2,
                            Points = 8f,
                            Position = 2,
                            PositionText = "2",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 3,
                            Points = 6f,
                            Position = 3,
                            PositionText = "3",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 4,
                            Points = 5f,
                            Position = 4,
                            PositionText = "4",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 5,
                            Points = 4f,
                            Position = 5,
                            PositionText = "5",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 6,
                            Points = 3f,
                            Position = 6,
                            PositionText = "6",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 7,
                            Points = 2f,
                            Position = 7,
                            PositionText = "7",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 8,
                            Points = 1f,
                            Position = 8,
                            PositionText = "8",
                            RaceId = 18,
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 1,
                            Points = 14f,
                            Position = 1,
                            PositionText = "1",
                            RaceId = 19,
                            Wins = 1
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 2,
                            Points = 11f,
                            Position = 3,
                            PositionText = "3",
                            RaceId = 19,
                            Wins = 0
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.LapTime", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DriverId");

                    b.Property<string>("Lap");

                    b.Property<int>("Milliseconds");

                    b.Property<int>("Position");

                    b.Property<int>("RaceId");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("LapTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 20,
                            Lap = "1",
                            Milliseconds = 98109,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:38.109"
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 20,
                            Lap = "2",
                            Milliseconds = 93006,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:33.006"
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 20,
                            Lap = "3",
                            Milliseconds = 92713,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.713"
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 20,
                            Lap = "4",
                            Milliseconds = 92803,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.803"
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 20,
                            Lap = "5",
                            Milliseconds = 92342,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.342"
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 20,
                            Lap = "6",
                            Milliseconds = 92605,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.605"
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 20,
                            Lap = "7",
                            Milliseconds = 92502,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.502"
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 20,
                            Lap = "8",
                            Milliseconds = 92537,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.537"
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 20,
                            Lap = "9",
                            Milliseconds = 93240,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:33.240"
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 20,
                            Lap = "10",
                            Milliseconds = 92572,
                            Position = 1,
                            RaceId = 841,
                            Time = "1:32.572"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.PitStop", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DriverId");

                    b.Property<string>("Duration");

                    b.Property<int?>("Lap");

                    b.Property<string>("Milliseconds");

                    b.Property<int?>("RaceId");

                    b.Property<int?>("Stop");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("PitStop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 153,
                            Duration = "26.898",
                            Lap = 1,
                            Milliseconds = "26898",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:05:23"
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 30,
                            Duration = "25.021",
                            Lap = 1,
                            Milliseconds = "25021",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:05:52"
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 17,
                            Duration = "23.426",
                            Lap = 11,
                            Milliseconds = "23426",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:20:48"
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 4,
                            Duration = "23.251",
                            Lap = 12,
                            Milliseconds = "23251",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:22:34"
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 13,
                            Duration = "23.842",
                            Lap = 13,
                            Milliseconds = "23842",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:24:10"
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 22,
                            Duration = "23.643",
                            Lap = 13,
                            Milliseconds = "23643",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:24:29"
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 20,
                            Duration = "22.603",
                            Lap = 14,
                            Milliseconds = "22603",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:25:17"
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 814,
                            Duration = "24.863",
                            Lap = 14,
                            Milliseconds = "24863",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:26:03"
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 816,
                            Duration = "25.259",
                            Lap = 14,
                            Milliseconds = "25259",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:26:50"
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 67,
                            Duration = "25.342",
                            Lap = 15,
                            Milliseconds = "25342",
                            RaceId = 841,
                            Stop = 1,
                            Time = "17:27:34"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.Qualification", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConstructorId");

                    b.Property<int>("DriverId");

                    b.Property<int>("Number");

                    b.Property<int>("Position");

                    b.Property<string>("Q1");

                    b.Property<string>("Q2");

                    b.Property<string>("Q3");

                    b.Property<int>("RaceId");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructorId = 1,
                            DriverId = 1,
                            Number = 22,
                            Position = 1,
                            Q1 = "1:26.572",
                            Q2 = "1:25.187",
                            Q3 = "1:26.714",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 2,
                            ConstructorId = 2,
                            DriverId = 9,
                            Number = 4,
                            Position = 2,
                            Q1 = "1:26.103",
                            Q2 = "1:25.315",
                            Q3 = "1:26.869",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 3,
                            ConstructorId = 1,
                            DriverId = 5,
                            Number = 23,
                            Position = 3,
                            Q1 = "1:25.664",
                            Q2 = "1:25.452",
                            Q3 = "1:27.079",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 4,
                            ConstructorId = 6,
                            DriverId = 13,
                            Number = 2,
                            Position = 4,
                            Q1 = "1:25.994",
                            Q2 = "1:25.691",
                            Q3 = "1:27.178",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 5,
                            ConstructorId = 2,
                            DriverId = 2,
                            Number = 3,
                            Position = 5,
                            Q1 = "1:25.960",
                            Q2 = "1:25.518",
                            Q3 = "1:27.236",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 6,
                            ConstructorId = 7,
                            DriverId = 15,
                            Number = 11,
                            Position = 6,
                            Q1 = "1:26.427",
                            Q2 = "1:26.101",
                            Q3 = "1:28.527",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 7,
                            ConstructorId = 3,
                            DriverId = 3,
                            Number = 7,
                            Position = 7,
                            Q1 = "1:26.295",
                            Q2 = "1:26.059",
                            Q3 = "1:28.687",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 8,
                            ConstructorId = 9,
                            DriverId = 14,
                            Number = 9,
                            Position = 8,
                            Q1 = "1:26.381",
                            Q2 = "1:26.063",
                            Q3 = "1:29.041",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 9,
                            ConstructorId = 7,
                            DriverId = 10,
                            Number = 12,
                            Position = 9,
                            Q1 = "1:26.919",
                            Q2 = "1:26.164",
                            Q3 = "1:29.593",
                            RaceId = 18
                        },
                        new
                        {
                            Id = 10,
                            ConstructorId = 5,
                            DriverId = 20,
                            Number = 15,
                            Position = 10,
                            Q1 = "1:26.702",
                            Q2 = "1:25.842",
                            Q3 = "NULL",
                            RaceId = 18
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.Race", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CircuitId");

                    b.Property<string>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Round");

                    b.Property<string>("Time");

                    b.Property<string>("Url");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitId = 1,
                            Date = "2009-03-29",
                            Name = "Australian Grand Prix",
                            Round = "1",
                            Time = "06:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Australian_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 2,
                            CircuitId = 2,
                            Date = "2009-04-05",
                            Name = "Malaysian Grand Prix",
                            Round = "2",
                            Time = "09:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Malaysian_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 3,
                            CircuitId = 17,
                            Date = "2009-04-19",
                            Name = "Chinese Grand Prix",
                            Round = "3",
                            Time = "07:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Chinese_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 4,
                            CircuitId = 3,
                            Date = "2009-04-26",
                            Name = "Bahrain Grand Prix",
                            Round = "4",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Bahrain_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 5,
                            CircuitId = 4,
                            Date = "2009-05-10",
                            Name = "Spanish Grand Prix",
                            Round = "5",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Spanish_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 6,
                            CircuitId = 6,
                            Date = "2009-05-24",
                            Name = "Monaco Grand Prix",
                            Round = "6",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Monaco_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 7,
                            CircuitId = 5,
                            Date = "2009-06-07",
                            Name = "Turkish Grand Prix",
                            Round = "7",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Turkish_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 8,
                            CircuitId = 9,
                            Date = "2009-06-21",
                            Name = "British Grand Prix",
                            Round = "8",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_British_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 9,
                            CircuitId = 20,
                            Date = "2009-07-12",
                            Name = "German Grand Prix",
                            Round = "9",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_German_Grand_Prix",
                            Year = "2009"
                        },
                        new
                        {
                            Id = 10,
                            CircuitId = 11,
                            Date = "2009-07-26",
                            Name = "Hungarian Grand Prix",
                            Round = "10",
                            Time = "12:00:00",
                            Url = "http://en.wikipedia.org/wiki/2009_Hungarian_Grand_Prix",
                            Year = "2009"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.RaceResult", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConstructorId");

                    b.Property<int>("DriverId");

                    b.Property<string>("FastestLap");

                    b.Property<string>("FastestLapSpeed");

                    b.Property<string>("FastestLapTime");

                    b.Property<int>("Grid");

                    b.Property<int>("Laps");

                    b.Property<string>("Milliseconds");

                    b.Property<string>("Number");

                    b.Property<float>("Points");

                    b.Property<string>("Position");

                    b.Property<int>("PositionOrder");

                    b.Property<string>("PositionText");

                    b.Property<int>("RaceId");

                    b.Property<string>("Rank");

                    b.Property<int>("StatusId");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("RaceResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructorId = 1,
                            DriverId = 1,
                            FastestLap = "39",
                            FastestLapSpeed = "218.3",
                            FastestLapTime = "01:27.5",
                            Grid = 1,
                            Laps = 58,
                            Milliseconds = "5690616",
                            Number = "22",
                            Points = 10f,
                            Position = "1",
                            PositionOrder = 1,
                            PositionText = "1",
                            RaceId = 18,
                            Rank = "2",
                            StatusId = 1,
                            Time = "34:50.6"
                        },
                        new
                        {
                            Id = 2,
                            ConstructorId = 2,
                            DriverId = 2,
                            FastestLap = "41",
                            FastestLapSpeed = "217.586",
                            FastestLapTime = "01:27.7",
                            Grid = 5,
                            Laps = 58,
                            Milliseconds = "5696094",
                            Number = "3",
                            Points = 8f,
                            Position = "2",
                            PositionOrder = 2,
                            PositionText = "2",
                            RaceId = 18,
                            Rank = "3",
                            StatusId = 1,
                            Time = "5.478"
                        },
                        new
                        {
                            Id = 3,
                            ConstructorId = 3,
                            DriverId = 3,
                            FastestLap = "41",
                            FastestLapSpeed = "216.719",
                            FastestLapTime = "01:28.1",
                            Grid = 7,
                            Laps = 58,
                            Milliseconds = "5698779",
                            Number = "7",
                            Points = 6f,
                            Position = "3",
                            PositionOrder = 3,
                            PositionText = "3",
                            RaceId = 18,
                            Rank = "5",
                            StatusId = 1,
                            Time = "8.163"
                        },
                        new
                        {
                            Id = 4,
                            ConstructorId = 4,
                            DriverId = 4,
                            FastestLap = "58",
                            FastestLapSpeed = "215.464",
                            FastestLapTime = "01:28.6",
                            Grid = 11,
                            Laps = 58,
                            Milliseconds = "5707797",
                            Number = "5",
                            Points = 5f,
                            Position = "4",
                            PositionOrder = 4,
                            PositionText = "4",
                            RaceId = 18,
                            Rank = "7",
                            StatusId = 1,
                            Time = "17.181"
                        },
                        new
                        {
                            Id = 5,
                            ConstructorId = 1,
                            DriverId = 5,
                            FastestLap = "43",
                            FastestLapSpeed = "218.385",
                            FastestLapTime = "01:27.4",
                            Grid = 3,
                            Laps = 58,
                            Milliseconds = "5708630",
                            Number = "23",
                            Points = 4f,
                            Position = "5",
                            PositionOrder = 5,
                            PositionText = "5",
                            RaceId = 18,
                            Rank = "1",
                            StatusId = 1,
                            Time = "18.014"
                        },
                        new
                        {
                            Id = 6,
                            ConstructorId = 3,
                            DriverId = 6,
                            FastestLap = "50",
                            FastestLapSpeed = "212.974",
                            FastestLapTime = "01:29.6",
                            Grid = 13,
                            Laps = 57,
                            Milliseconds = "",
                            Number = "8",
                            Points = 3f,
                            Position = "6",
                            PositionOrder = 6,
                            PositionText = "6",
                            RaceId = 18,
                            Rank = "14",
                            StatusId = 11,
                            Time = ""
                        },
                        new
                        {
                            Id = 7,
                            ConstructorId = 5,
                            DriverId = 7,
                            FastestLap = "22",
                            FastestLapSpeed = "213.224",
                            FastestLapTime = "01:29.5",
                            Grid = 17,
                            Laps = 55,
                            Milliseconds = "",
                            Number = "14",
                            Points = 2f,
                            Position = "7",
                            PositionOrder = 7,
                            PositionText = "7",
                            RaceId = 18,
                            Rank = "12",
                            StatusId = 5,
                            Time = ""
                        },
                        new
                        {
                            Id = 8,
                            ConstructorId = 6,
                            DriverId = 8,
                            FastestLap = "20",
                            FastestLapSpeed = "217.18",
                            FastestLapTime = "01:27.9",
                            Grid = 15,
                            Laps = 53,
                            Milliseconds = "",
                            Number = "1",
                            Points = 1f,
                            Position = "8",
                            PositionOrder = 8,
                            PositionText = "8",
                            RaceId = 18,
                            Rank = "4",
                            StatusId = 5,
                            Time = ""
                        },
                        new
                        {
                            Id = 9,
                            ConstructorId = 2,
                            DriverId = 9,
                            FastestLap = "15",
                            FastestLapSpeed = "215.1",
                            FastestLapTime = "01:28.8",
                            Grid = 2,
                            Laps = 47,
                            Milliseconds = "",
                            Number = "4",
                            Points = 0f,
                            Position = "",
                            PositionOrder = 9,
                            PositionText = "R",
                            RaceId = 18,
                            Rank = "9",
                            StatusId = 4,
                            Time = ""
                        },
                        new
                        {
                            Id = 10,
                            ConstructorId = 7,
                            DriverId = 10,
                            FastestLap = "23",
                            FastestLapSpeed = "213.166",
                            FastestLapTime = "01:29.6",
                            Grid = 18,
                            Laps = 43,
                            Milliseconds = "",
                            Number = "12",
                            Points = 0f,
                            Position = "",
                            PositionOrder = 10,
                            PositionText = "R",
                            RaceId = 18,
                            Rank = "13",
                            StatusId = 3,
                            Time = ""
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.ResultStatus", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("ResultStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Finished"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Disqualified"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Accident"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Collision"
                        },
                        new
                        {
                            Id = 5,
                            Status = "Engine"
                        },
                        new
                        {
                            Id = 6,
                            Status = "Gearbox"
                        },
                        new
                        {
                            Id = 7,
                            Status = "Transmission"
                        },
                        new
                        {
                            Id = 8,
                            Status = "Clutch"
                        },
                        new
                        {
                            Id = 9,
                            Status = "Hydraulics"
                        },
                        new
                        {
                            Id = 10,
                            Status = "Electrical"
                        });
                });

            modelBuilder.Entity("Formula_1_API.Models.Season", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "http://en.wikipedia.org/wiki/2009_Formula_One_season",
                            Year = 2009
                        },
                        new
                        {
                            Id = 2,
                            Url = "http://en.wikipedia.org/wiki/2008_Formula_One_season",
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            Url = "http://en.wikipedia.org/wiki/2007_Formula_One_season",
                            Year = 2007
                        },
                        new
                        {
                            Id = 4,
                            Url = "http://en.wikipedia.org/wiki/2006_Formula_One_season",
                            Year = 2006
                        },
                        new
                        {
                            Id = 5,
                            Url = "http://en.wikipedia.org/wiki/2005_Formula_One_season",
                            Year = 2005
                        },
                        new
                        {
                            Id = 6,
                            Url = "http://en.wikipedia.org/wiki/2004_Formula_One_season",
                            Year = 2004
                        },
                        new
                        {
                            Id = 7,
                            Url = "http://en.wikipedia.org/wiki/2003_Formula_One_season",
                            Year = 2003
                        },
                        new
                        {
                            Id = 8,
                            Url = "http://en.wikipedia.org/wiki/2002_Formula_One_season",
                            Year = 2002
                        },
                        new
                        {
                            Id = 9,
                            Url = "http://en.wikipedia.org/wiki/2001_Formula_One_season",
                            Year = 2001
                        },
                        new
                        {
                            Id = 10,
                            Url = "http://en.wikipedia.org/wiki/2000_Formula_One_season",
                            Year = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
