name: formula-1-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [live]
    paths:
      # - "Formula-1-Web/**"
      - "**"
      - ".github/workflows/web-AutoDeployTrigger-2a37c845-b113-4e75-85d9-9b81bbaf6e31.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: Formula-1-Web
          acrName: formula1registry
          acrUsername: ${{ secrets.DB_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.DB_REGISTRY_PASSWORD }}
          containerAppName: test-web
          resourceGroup: Formula1ResourceGroup
          imageToBuild: formula1registry.azurecr.io/web:${{ github.sha }}
          location: ${{ secrets.AZURE_LOCATION }}
          # containerAppEnvironment: formula-1-app-env
          containerAppEnvironment: test-env
